
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhtnruktmtjqrfoiyrep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpodG5ydWt0bXRqcXJmb2l5cmVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NTczMzksImV4cCI6MjA1NzMzMzMzOX0._HZzAtVcTH_cdXZoxIeERNYqS6_hFEjcWbgHK3vxQBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Add debug info to track instance creation
console.log('[DEBUG] Creating Supabase client with URL:', SUPABASE_URL);

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  // Remove any restrictions on database and storage
  db: {
    schema: 'public',
  },
  global: {
    fetch: (url, options) => {
      console.log('[DEBUG] Supabase fetch request to:', url);
      return fetch(url, options);
    },
    headers: { 
      'x-app-version': '1.0.0',
      // Allow all origins
      'Access-Control-Allow-Origin': '*',
    },
  },
});

// Log when authenticated state changes
supabase.auth.onAuthStateChange((event, session) => {
  console.log('[DEBUG] Auth state changed:', event);
  if (session?.user) {
    console.log('[DEBUG] User signed in:', session.user.email);
  }
});

console.log('[DEBUG] Supabase client initialized');
